// Generated by scripts/generate-build-info.sh — do not edit.
import Foundation

enum BuildInfo {
    static let gitSHA = "82ed367"
    static let builtAt = "2026-08-23T18:32:24Z"

    static var menuLabel: String {
        let version = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "?"
        let build = Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "?"
        return "v\(version) (\(build)) • \(gitSHA) • \(builtAt)"
    }
}
